#  AMBERSONG  -  the portal page, gzipped at build time
#
#  WHY THIS EXISTS.
#  The page was being sent uncompressed on every load, over a server that
#  handles one connection at a time. Measured on the machine when it was 21 kB:
#  0.7 to 3.6 seconds, which was the entire reason the portal felt slow. Nothing
#  about the page's DESIGN was the problem; its size was.
#
#  Gzip takes it to a little over a third (the generated header records the
#  exact sizes of each build), and every browser has understood
#  Content-Encoding: gzip for twenty-five years. The ETag then removes the cost
#  on a reload - the browser asks, the radio answers 304 with an empty body,
#  and the page itself does not cross the wifi again.
#
#  Compressing at BUILD time rather than at run time matters: it is done once,
#  on the PC, instead of spending the radio's CPU on it at each request.

import gzip, hashlib, io, os

Import("env")

SRC = os.path.join("data", "portal.html")
OUT = os.path.join("src", "s3", "page_gz.h")


def check_js(html_text):
    """Refuse to build a page whose script will not parse.

    THE REASON THIS EXISTS. A duplicate `const t` was shipped to the machine and
    made the WHOLE script fail to parse, so the portal rendered a dead page - and
    it was found by the author, on the hardware, not by anyone reading the code.
    A syntax error is the one class of bug a machine can catch for free, and it
    had been costing a flash cycle and a person's patience each time.

    The build FAILS here rather than warning. A page that cannot parse is not a
    page.
    """
    a = html_text.find("<script>")
    b = html_text.find("</script>")
    if a < 0 or b < 0:
        return
    js = html_text[a + len("<script>"):b]
    try:
        import esprima
    except ImportError:
        print("  [WARN] esprima not installed - the portal's script was NOT checked.")
        print("         pip install esprima")
        return
    try:
        esprima.parseScript(js)
    except Exception as e:
        raise Exception("portal script will not parse: %s" % e)
    print("  portal script: %d bytes, parses cleanly" % len(js))


def build_page(source, target, env):
    with io.open(SRC, encoding="utf-8", newline="") as f:
        text = f.read()
    check_js(text)
    html = text.encode("utf-8")

    #  mtime=0 so an unchanged page produces an unchanged blob, which keeps the
    #  ETag stable and the browser's cache valid across rebuilds.
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as g:
        g.write(html)
    blob = buf.getvalue()

    etag = hashlib.sha256(blob).hexdigest()[:16]

    lines = []
    lines.append("//  GENERATED by scripts/page.py from data/portal.html - DO NOT EDIT.")
    lines.append("//  Edit the HTML there; this file is rebuilt every compile.")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append('//  %d bytes of HTML -> %d gzipped (%.0f%%)'
                 % (len(html), len(blob), 100.0 * len(blob) / len(html)))
    lines.append('static const char PAGE_ETAG[] PROGMEM = "%s";' % etag)
    lines.append("static const size_t PAGE_GZ_LEN = %d;" % len(blob))
    lines.append("static const uint8_t PAGE_GZ[] PROGMEM = {")
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("  " + ",".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("")

    text = "\n".join(lines)

    #  Only rewrite when it actually changed, so an untouched page does not
    #  force a rebuild of everything that includes it.
    old = None
    if os.path.exists(OUT):
        with io.open(OUT, encoding="utf-8", newline="") as f:
            old = f.read()
    if old != text:
        with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)

    print("  portal page: %d bytes -> %d gzipped (%.0f%%), etag %s"
          % (len(html), len(blob), 100.0 * len(blob) / len(html), etag))


build_page(None, None, env)
